### PR TITLE
Upgrade to 2022.3.8 LTS

### PR DESCRIPTION
**Pull request by mikeskydev**
Upgrade to the latest LTS version of Unity. Will need testing before merging.

### CODE REVIEW

**Comment by mikeage** [comment]
Please hold off on this one for a bit because of caching issues.

**Comment by mikeage** [comment]
Also, it looks like the builds failed because we're still on the older version of the game-ci action. If #505 get merged, then these should be good to go

**Comment by mikeage** [comment]
Because this came from an org's fork and not  personal one, I can't update it. Please ping me on Discord to coordinate a sync and build

**Comment by mikeage** [comment]
Oops, I forgot that PRs and branches won't save caches. It'll take a while, but you don't need to worry about pushing something important out of the cache.

**Comment by mikeskydev** [comment]
@mikeage we'll have to hold off until #503 as it seems the android builds failed because 2022 LTS needs at least targeting of v30 :(

**Pull request closed without merging**
