### PR TITLE
Update lots of shaders to singlepass

### PR DESCRIPTION
**Pull request by mikeskydev**
Updates the majority of our shaders to support single pass instanced rendering.

Notable exception is SE Natural Bloom which is fairly complicated, and we may be switching it soon anyways.

### CODE REVIEW

**Comment by mikeskydev** [comment]
Probably worth checking the CI with our supported android platforms before merging. :)

**Comment by mikeage** [comment]
I expected the CI to need to recompile all of the shaders, but it doesn't seem to have needed to (at least based on the amount of time it took and lines like `finished in 0.00 seconds. Local cache hits 12 (0.01s CPU time), remote cache hits 0 (0.00s CPU time), compiled 0 variants (0.00s CPU time), skipped 0 variants`. I don't know anything about how shader compilation works, but did this... work?

**Review by andybak — APPROVED** [review]
I'd be also tempted to allow switching to single pass via a config setting. Maybe a separate PR? Would reduce the friction for testing in builds.

**Comment by mikeskydev** [comment]
Ideally this should be a set and done, I just need more time to investigate! I also think it's worth temporarily delaying a switch while you've got new shaders dropping imminently.

**Pull request merged**
