### PR TITLE
Feature/sketchfab improvements

### PR DESCRIPTION
**Pull request by andybak**
Wording changes related to login and upload.

Outstanding issue:

We default to exporting as "private" with Sketchfab. However this requires a paying account.

Sketchfab has no meaningful error message when the user tries to publish as "private" on a free account (You just get some text about a 403 error).

Most users will assume this is something they cannot fix themselves. I propose we change the default to "public" and add some text somewhere telling people to change it if they have a paid account.

### CODE REVIEW

**Comment by andybak** [comment]
> LGTM! Is it even an option to immediately do a public upload on Sketchfab? There wasn't for Poly, at least.

I think so - but if not we need a different solution.

Ideally Sketchfab would fix it at their end but until that happens we need to mitigate the confusion. It fooled me so it's not just an issue for non-technical users.

**Comment by andybak** [comment]
@mikeskydev from our upload code:

            var moreParams = new List<(string, string)>
            {
                ("name", name),
                ("source", "open-brush"),
                ("private", "true"), // TODO: remove when this feature is not secret
                // https://docs.sketchfab.com/data-api/v3/index.html#!/models/post_v3_models
                // "Enables 2D view in model inspector. All downloadable models must have isInspectable
                // enabled."
                ("isInspectable", "true"),
                // ??? https://docs.sketchfab.com/data-api/v3/index.html#!/licenses/get_v3_licenses
                ("license", "by-sa"),
                // This is how you specify multiple tags:
                // ("tags", "[\"tiltbrush\", \"some-other-tag\"]"),
                ("tags", "[\"openbrush\", \"tiltbrush\"]"),
                ("isPublished", "false"),
                // ("description", "Dummy description"),
            };

**Review by mikeage — APPROVED** [review]

**Comment by mikeskydev** [comment]
> remove when this feature is not secret

Now, then? :D

**Comment by andybak** [comment]
> > remove when this feature is not secret
> 
> Now, then? :D

Yeah. Weird. There's good reasons to not default to public - which is what is giving me pause.

But I think "default to public with a clear message to that effect" is acceptable. Do you agree @mikeskydev ?

**Comment by mikeskydev** [comment]
It gives me a bit of pause too, i'd like to revisit it with an option, shall we leave it for now?

**Pull request merged**
