### PR TITLE
Preview spheres for 360 images

### PR DESCRIPTION
**Pull request by andybak**
image

(Now I see that screengrab it reminds me I should fix the text title wrapping while I'm here)

### CODE REVIEW

**Comment by andybak** [comment]
(This needs a fix for single-pass but I'll wait for #677 to merge before I look at that)

**Comment by mikeage** [comment]
677 is merged now :-)

**Comment by andybak** [comment]
Ironed out a final Quest weirdness. I think this is good to go. 

@mikeage ?

**Review by mikeage — COMMENTED** [review]
LGTM, but I'd prefer to separate the panel placement into a distinct PR

**Comment by andybak** [comment]
Once #697 has finished doing it's thing, are you happy with a merge for this? @mikeage

**Comment by mikeage** [comment]
Yes

**Pull request merged**
