### PR TITLE
Better normal map exports

### PR DESCRIPTION
**Pull request by andybak**
We currently export grayscale height maps instead of proper normal maps and fix this in the shader. I don't know the reason for this but for any export targets that don't use our shaders (Blender, Godot, Unreal etc etc) this means even brushes that can use fairly standard PBR shaders look pretty bad.

### CODE REVIEW

**Comment by andybak** [comment]
This is a pretty old PR. I've been keeping it in sync with main but looking back, I have a couple of concerns:

1. I can't recall how I did the conversion but the Unity Editor has an API that matches what happens automatically on import so we should use that (assuming I didn't originally)
2. The changes to the materials look a bit concerning. I probably accepted whatever Unity did automatically but I'd like to redo it and see if we get the same diff.

**Comment by andybak** [comment]
Also see #308 for some other issues that probably need considering.

**Comment by mikeskydev** [comment]
Some of those imports seem to have dramatically changed some import settings in the .meta files for the textures too, should probably give everything a proper check?

**Comment by andybak** [comment]
Yeah - that's pretty much what I mean with my point 2 above. I'm going to redo this PR so I should probably make it draft in the meantime.

**Pull request closed without merging**
