### PR TITLE
Fixes for Quest Accounts Panel showing Desktop version

### PR DESCRIPTION
**Pull request by andybak**

### CODE REVIEW

**Comment by mikeage** [comment]
This PR was built from a branch, so it has the secrets. Only PRs from forks (e.g.,the IxxyXR repo) don't have access to the secrets.

**Comment by andybak** [comment]
> This PR was built from a branch, so it has the secrets. Only PRs from forks (e.g.,the IxxyXR repo) don't have access to the secrets.

hmmmm. in which case i'll need to dig deeper.

**Comment by andybak** [comment]
Previous comment was meant for @mikeskydev ...

**Comment by mikeskydev** [comment]
@andybak Yeah, it shows one of the option windows when it shouldn't right? that's fine, just the error I was seeing when testing was that clicking 'sign in' prompted to remove headset. if it's back to the other bug, that's fine, i'll tackle that seperately!

**Comment by andybak** [comment]
I just compared to pre 1.0 and there were a few differences in which game objects were visible initially. I've pushed a change that fixes this

**Comment by mikeskydev** [comment]
Authentication appears to be a different issue, so i'm happy for this to be merged in the meantime

**Pull request merged**
