### PR TITLE
Enable file system watcher on mobile

### PR DESCRIPTION
**Pull request by andybak**
Let's see if this works now

### CODE REVIEW

**Comment by mikeskydev** [comment]
Please can this be tested on Q1!

**Comment by andybak** [comment]
> Please can this be tested on Q1!

I don't currently have access to a Quest 1. Do you?

**Comment by mikeage** [comment]
I can test Q1 tonight, just please tell me what specifically to look out for

**Comment by andybak** [comment]
This fixes the bug on Quest 3 at least. @mikeage - I think we just need to test that it doesn't make anything *worse* on Quest 1.

Try using the Media Library browser and see if it does anything weird. 

If it's working, then you should be able to add new images into the media library with Open Brush running and see them appear as previews in the Media Library panel instantly.

If it's not working but not breaking stuff then they just won't appear.

If it's breaking stuff then... dunno. Weird stuff will happen?

**Comment by mikeage** [comment]
Works on Q1. Pushing or deleting an image immediately brings up the "loading images" screen and then the new one is seen automatically.

@mikeskydev , do we need to test other platforms, Pico, etc.? Or did you ask about Q1 because that's the only one you don't have.

**Comment by mikeskydev** [comment]
I was mainly concerned about the performance implications of the watcher, but that sounds fine!

**Comment by mikeage** [comment]
it didn't seem to cause anything  (assuming it's inotify under the hood, it should be zero impact)

**Comment by mikeage** [comment]
I'm approving, but let's not merge until I fix the DMG build

**Review by mikeage — APPROVED** [review]

**Comment by mikeage** [comment]
this is ready to go, as soon as the build on `main` finishes

**Pull request merged**
