### PR TITLE
Zapbox: Set to iPhone only for now

### PR DESCRIPTION
**Pull request by mikeskydev**
Will need changing when we deploy ARKit based app.

### CODE REVIEW

**Review by mikeage — APPROVED** [review]
LGTM. We have a bunch of places that assume iPhone == Zapbox, but that's fine; we'll revisit it if / when we do ARKit. Shouldn't be too bad

**Comment by andybak** [comment]
> we'll revisit it if / when we do ARKit. 

I'd like to ship view-only mode before that. All that needs is an iOS build that doesn't show an error screen if the Zapbox isn't detected.

**Comment by mikeage** [comment]
> > we'll revisit it if / when we do ARKit.
> 
> I'd like to ship view-only mode before that. All that needs is an iOS build that doesn't show an error screen if the Zapbox isn't detected.

Even better! I assume two separate releases would be probably be more user friendly, but we have the infra to do this now

**Comment by mikeskydev** [comment]
With the way zapbox works it's an all or nothing SDK, we'll either always have a separate build that loads zapbox, or somehow figure out a button to launch zapbox mode from the main build

**Pull request merged**
