### PR TITLE
Monoscopic for all builds

### PR DESCRIPTION
**Pull request by andybak**
1. Make monoscopic a config file setting
2. Allow XR SDKs to be disabled via a config file setting
3. A couple of keyboard shortcuts that work during launch to trigger the two modes above

### CODE REVIEW

**Comment by mikeage** [comment]
On my Mac, I get this screen on bootup (after the OB logo):

Screenshot 2024-03-05 at 15 46 21

Clicking on the X closes the app. 

Looking at the logs, I have a billion and a half NREs.

These are the first:

```
NullReferenceException: Object reference not set to an instance of an object
  at TiltBrush.VrSdk.Initialize () [0x00005] in <07fc4dfba3ec4f759d53eb344c2946cb>:0 
  at TiltBrush.VrSdk.Awake () [0x0006a] in <07fc4dfba3ec4f759d53eb344c2946cb>:0 

NullReferenceException: Object reference not set to an instance of an object
  at TiltBrush.InputManager.ShowControllers (System.Boolean show) [0x00024] in <07fc4dfba3ec4f759d53eb344c2946cb>:0 
  at TiltBrush.InputManager.OnEnable () [0x00006] in <07fc4dfba3ec4f759d53eb344c2946cb>:0 
```

**Comment by andybak** [comment]
@mikeage spotted odd behaviour in builds for some platforms. This might be trickier than expected.

**Comment by mikeage** [comment]
Could it be as simple as needing to force Monoscopic mode in the config file for Mac?

**Comment by mikeage** [comment]
Ok, good news. If I set the flag in the CFG on Mac, it works out of the box. 

That should be easy enough to also set with an `#if` in the code. 

No idea about any other platforms, though :-)

**Comment by mikeage** [comment]
What does disabling XR mean in this context?

**Comment by andybak** [comment]
> What does disabling XR mean in this context?

Well - on a Mac it is a bit meaningless. In terms of code it's "don't try and initialize XR - just assume it's not there" We should probably just force that setting on for platforms with no XR support (Mac basically)

**Comment by andybak** [comment]
To be honest - it was about working with the logic flow as it currently stands rather than presenting a sane end-user experience. We already have logic around switching to "view only mode" so I added an override to force this even when a headset is detected.

And there's completely separate logic about monoscopic so I added another override there.

To some extent it's laziness - or to put it more charitably "a desire to minimize code changes and lessen the probability of introducing bugs"

**Comment by mikeage** [comment]
Ok, there's a view only mode of some form that's different from Monoscopic. That's the part I was missing.

**Comment by mikeage** [comment]
Mac build looks good

**Comment by mikeage** [comment]
I don't know if I agree with eb1bd471e8bb424d618da7534fcd1f22064c9bb9 . View only mode doesn't work on the Mac, although with the new scale, it does look different.

Although we do have a new NRE starting things off:

```
NullReferenceException: Object reference not set to an instance of an object
  at TiltBrush.VrSdk.IsHmdInitialized () [0x00011] in <ca62260783cd425d92b3fd5d087e7871>:0
  at ViewModeUI.Awake () [0x0000b] in <ca62260783cd425d92b3fd5d087e7871>:0
  ```

**Comment by andybak** [comment]
> I don't know if I agree with https://github.com/icosa-foundation/open-brush/commit/eb1bd471e8bb424d618da7534fcd1f22064c9bb9 .

Not sure what you quite mean by "agree"? Previously there was no way to get into View only mode. Monoscopic mode is much more niche and a lower priority so the previous behaviour was just, plain wrong.

**Comment by andybak** [comment]
> > I don't know if I agree with [eb1bd47](https://github.com/icosa-foundation/open-brush/commit/eb1bd471e8bb424d618da7534fcd1f22064c9bb9) .
> 
> Not sure what you quite mean by "agree"? Previously there was no way to get into View only mode. Monoscopic mode is much more niche and a lower priority so the previous behaviour was just, plain wrong.

To put it another way - the previous behaviour was a mistake - not an intentional thing.

**Comment by mikeage** [comment]
The previous behavior matched this comment from Discord:

> i'm going to force mono on for MacOS

I think this is sensible, at least until the view-only mode works on Mac. No sense defaulting (or even exposing!) something that doesn't work.

**Comment by andybak** [comment]
If I can't fix view-only mode then that's ok as an interim solution but two of my goals were:

1. Have all platforms behaving consistently
2. Have view-only mode easily available on all platforms

**Comment by mikeage** [comment]
Fair. I feel like this PR might depend on a different one called "Fix View-only mode on Mac" (and maybe Linux? I dunno), but maybe it has value even if that one isn't complete. In that case, defaulting to Monoscopic mode on Mac seems sensible. If the view-only mode works, then I absolutely agree about prioritizing it over monoscopic

**Comment by andybak** [comment]
MacOS appears to be fixed.

**Comment by mikeage** [comment]
Text looks good on a Mac, at least, but the keys are broken now (or at least, I couldn't get them to work). I think it's because of the order. Is it possible to use the key to change the UserConfig value rather than put it into an if at load time?

**Comment by mikeage** [comment]
> > but the keys are broken now (or at least, I couldn't get them to work). I think it's because of the order. Is it possible to use the key to change the UserConfig value rather than put it into an if at load time?
> 
> I'll probably just create an issue for now. Shortcut keys to trigger these modes is a "nice to have" at this stage. It will become more critical once you can set these modes from the UI as people might get themselves into a mode by accident. We'll also need a proper settings UI for both non-VR modes at that point.

I'm fine with that, but I don't think they work at all. Maybe best to just remove it, and make it selectable from the cfg file only? 

For Mac and Linux, which never have a VR mode, do you think the default should be View (like Windows) or Monoscopic (like today's build)?

**Comment by andybak** [comment]
> I'm fine with that, but I don't think they work at all. Maybe best to just remove it, and make it selectable from the cfg file only?

Yep. I might comment it out with a TODO to make it easier to recall what I was doing.

> For Mac and Linux, which never have a VR mode, do you think the default should be View (like Windows) or Monoscopic (like today's build)?

The default should always be View - monoscopic is an niche use case at the moment (unless we massively overhaul it's usability one day)

**Comment by mikeage** [comment]
I'm not 100% sure I agree about the default being View on Mac / Linux, since up to now, that hasn't been. Are you open to arguing about this? :-)

**Comment by andybak** [comment]
> I'm not 100% sure I agree about the default being View on Mac / Linux, since up to now, that hasn't been. Are you open to arguing about this? :-)

Yeah! Go ahead. :)

My argument is that this isn't a new version of the monoscopic build at all. It's just our default build for platforms where we didn't have a proper build before. The miniscule number of people that used monoscopic mode can still do so by using this build and setting the config option.

There's potentially a much bigger group of people who would find a non-VR View-only mode useful.

I guess my main point is that "View Only mode" is something worth promoting - whereas monoscopic mode is useful to a handful of people - devs and people playing with scripting. I doubt *anyone* is using it for drawing (because it's really hard to use!)

**Comment by mikeage** [comment]
Ok, so first of all, I agree with you for Windows, and if there was a meaning to Quest-without-a-headset, I'd agree there too!

For Linux and Mac, though, we've released a build up to now that runs in Monoscopic only. I'm not sure I like the idea of changing that suddenly, even if we rename everything (which we need to do in any case, I think, since even if it's Monoscopic-with-View mode, it still should just be called "Mac" or "Linux").

If we can get a mention of Monoscopic in the initial text, then I'm ok with changing the default. People will be surprised for 5 seconds, and then figure out what to do. 

Monoscopic mode is awful for drawing. Agreed. It's a nifty way to work with the API, though, and it's actually not a terribly viewer either (but not as good).

**Comment by andybak** [comment]
> If we can get a mention of Monoscopic in the initial text, then I'm ok with changing the default.

That sounds like an acceptable compromise. I didn't bother because:

a) laziness
b) there's an awful lot of text on that page anyway

But if you think it's important for the ~0 users that are using Mac or Linux monoscopic then I'm happy to do it. ;-)

>  even if we rename everything 

Yep. We should. Will you or shall I?

**Comment by mikeage** [comment]
I don't mind renaming, but you have to do the text :-)

**Comment by mikeage** [comment]
Screenshot 2024-04-03 at 14 34 42

No URL, but I do have the text...

**Comment by mikeage** [comment]
Works beautifully! The page itself should be updated after (as?) this is merged, but the UX is great

**Comment by andybak** [comment]
I've got a revised page mostly ready to go. I'll merge that when this hits beta and add a note for non-beta users.

I think my plan is to merge #620 to main, merge this into #573 for final testing and then hopefully merge #573 next week.

Sound ok?

**Comment by mikeage** [comment]
I thought you wanted to merge this and 620, but either way, sounds good.

**Comment by andybak** [comment]
Yes you're correct. I was getting mixed up as all three affect experimental flags/user config options stuff (which is why testing is a hassle)

But the effects of 573 are more isolated so that one can go separately.

**Pull request closed without merging**
